config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords:     'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  root 'items#index'

  resources :items, only: [:show, :index, :new, :create, :edit, :update, :destroy] do
    member do
      get :purchase_top
      post :purchase
    end
    collection do
      get :search
    end
  end

  resources :categories, only: [:show, :index]


  resources :brands, only: [:show, :index]

  get 'users/sign_up_top' => 'users#top'
  get '/users/after_signup' => 'users#after_signup'
  get '/signup/registration' => 'users#registration'
  get '/users/mypage/' => 'users#show'
  get '/users/mypage/identification' => 'users#identification'
  get '/users/mypage/logout' => 'users#logout'
  get '/users/mypage/profile' => 'users#profile'
  get '/users/mypage/card' => 'users#card'
  get '/users/mypage/items' => 'users#items'
  get '/users/mypage/salingitem/:id' => 'users#item'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: %i[facebook google_oauth2]
  validates :first_name, :last_name,:prefecture, :city, :address, :birth_year,:birth_month, :birth_day, presence: true
  validates :first_name_kana, :last_name_kana, presence: true, format: { with: /\A[\p{katakana}]+\z/}
  validates :phone_number, presence: true, format: { with: /\A0[5789]0\d{8}\z/ }, length: { is: 11}
  validates :nickname, presence: true
  validates :credit_card_num, presence: true, format: { with: /\A[0-9]+\z/}
  validates :credit_card_expiration_month, :credit_card_expiration_year, presence: true, format: { with: /\A[0-9]{2}\z/}, length: { is: 2}
  validates :credit_card_security_num, presence: true, format: { with: /\A[0-9]+\z/}
  validates :postal_code, format: {with: /\A\d{7}\z/}, allow_blank: true, length: { is: 7}
  validates :password, confirmation: true, length: { minimum: 6 }, presence: true, on: :create
  validates :email, uniqueness: true, presence: true

  has_many :salling_items, class_name: "Item"
  has_many :bought_items, class_name: "Item"


  def purchase(item,token)
    Payjp.api_key = ENV['PAYJP_SECRET_KEY']

    @purchase = Payjp::Charge.create(currency: 'jpy', amount: item.price, card: token )
    item.update(buyer_id: id)
  end



  def self.find_for_omniauth(auth)
    user = User.where(email: auth.info.email, provider: auth.provider).first
    unless user
      user = User.new(nickname:auth.info.name,
                       provider: auth.provider,
                       uid:      auth.uid,
                       email:    auth.info.email,
                       password: Devise.friendly_token[0,20],)
    end
    user
  end

  enum prefecture: { 北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
    茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
    新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
    岐阜県:21,静岡県:22,愛知県:23,三重県:24,
    滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
    鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
    徳島県:36,香川県:37,愛媛県:38,高知県:39,
    福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,沖縄県:47}



  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end
    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    @user = User.find_for_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
    else
      render template: 'devise/registrations/new'
    end
  end

  def google_oauth2
    @user = User.find_for_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
    else
      render template: 'devise/registrations/new'
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]



  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def update_resource(resource, params)
    resource.update_without_current_password(params)
  end

  def after_update_path_for(resource)
    users_mypage_path
  end


  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    users_after_signup_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  layout "mypage_layout", only: [:show, :identification, :logout, :card, :profile, :items]
  before_action :set_layout, only:[:show, :identification, :card, :profile, :items]

  def top
  end

  def after_signup
  end

  def registration
  end

  def identification
  end

  def show


  end

  def profile

  end

  def logout
  end

  def card
  end

  def item
    @item = Item.includes(:item_images).find(params[:id])
    @item_images = @item.item_images
    @saler = current_user
    set_category
  end

  def items
    @items = Item.includes(:item_images).where(saler_id: @user.id)
  end

  private
  def set_layout
    @user = current_user
    redirect_to root_path, notice: "not signed in!!" unless @user
  end

  def set_category
    @category = @item.category
    @parent_category = @category.parent
    @grandparent_category = @category.root
  end
end

app/views/users/_sidebar.html.haml
.l-side
%nav.mypage-nav
  %ul.mypage-nav-list
    %li
      = link_to "マイページ", users_mypage_path, class: "mypage-nav-list-item"
    %li
      = link_to "お知らせ", '#', class: "mypage-nav-list-item"
      %span.mypage-nav-number
    %li
      = link_to "やることリスト", '#', class: "mypage-nav-list-item"
    %li
      = link_to "いいね！一覧", '#', class: "mypage-nav-list-item"
    %li
      = link_to "出品する", '#', class: "mypage-nav-list-item"
    %li
      = link_to "出品中", users_mypage_items_path, class: "mypage-nav-list-item"
    %li
      = link_to "取引中", '#', class: "mypage-nav-list-item"
    %li
      = link_to "売却済み", '#', class: "mypage-nav-list-item"
    %li
      = link_to "取引中", '#', class: "mypage-nav-list-item"
    %li
      = link_to "過去の取引", '#', class: "mypage-nav-list-item"
    %li
      = link_to "ニュース一覧", '#', class: "mypage-nav-list-item"
    %li
      = link_to "評価一覧", '#', class: "mypage-nav-list-item"
    %li
      = link_to "ガイド", '#', class: "mypage-nav-list-item"
    %li
      = link_to "お問い合わせ", '#', class: "mypage-nav-list-item"
  %h3.mypage-nav-head 売上・ポイント
  %ul.mypage-nav-list
    %li
      = link_to "売上・振込申請", '#', class: "mypage-nav-list-item"
    %li
      = link_to "ポイント", '#', class: "mypage-nav-list-item"
  %h3.mypage-nav-head 設定
  %ul.mypage-nav-list
    %li
      = link_to "プロフィール", users_mypage_profile_path , class: "mypage-nav-list-item"
    %li
      = link_to "住所変更", '#', class: "mypage-nav-list-item"
    %li
      = link_to "支払い方法", users_mypage_card_path, class: "mypage-nav-list-item"
    %li
      = link_to "パスワード", '#', class: "mypage-nav-list-item"
    %li
      =link_to "本人情報", users_mypage_identification_path, class: "mypage-nav-list-item"
    %li
      = link_to "電話番号の確認", '#', class: "mypage-nav-list-item"
    %li
      = link_to "ログアウト", users_mypage_logout_path, class: "mypage-nav-list-item"
</div

app/views/users/after_signup.html.haml
.signup-container
  %header.signup-header
    = render '/layouts/accounts/headerLogo'
    %nav.progress-bar.signup-bar
      %ol.clearfix
        %li.progress.through#step
          会員情報
          .progress-status
        %li.progress.through#step
          電話番号認証
          .progress-status
        %li.progress.through#step
          住所入力
          .progress-status
        %li.progress.through#step
          支払い方法
          .progress-status
        %li.progress.active#step
          完了
          .progress-status
  %main.signup-main
    %section.l-signup-container
      %h2.l-signup-head 会員登録完了
      .l-signup-inner
        .l-signup-content
          ありがとうございます。
          %br/
          会員登録が完了しました。
        = link_to "メルカリをはじめる", root_path, class: 'button btn-default btn-red'
  %footer.signup-footer
    = render '/layouts/accounts/footer'

app/views/users/card.html.haml
.user-card
  .user-card__header
    %h2 クレジットカード情報登録
  .user-card__inner
    = form_for @user, url: user_registration_path do |f|
      = render 'devise/form/cardInfo', {f: f}
      .user-card__inner--btn
        = f.submit "追加する", class: "btn-default btn-red"

app/views/users/identification.html.haml
.identification-content
  %h2.identification-content__header-text 本人情報の登録
  %p.identification-content__text お客さまのあんしん・あんぜんな取引のため、本人情報のご登録をお願いしております。
  = form_for @user, url: user_registration_path do |f|
    = render '/devise/form/addressInfo', {f: f}

    %p.identification-content__birthday-text ※出品されたことがある、本人情報未登録のお客さまもご対象となります。
    .actions
    = f.submit "登録する", id: "SaveAccount", class: "btn-default btn-red"
    .identification-content__bottom-text
      %p 
        =link_to "" do
          本人情報の確認について
          %i.icon-arrow-right 

app/views/users/item.html.haml
%header.header-content
  = render 'shared/header'
%section.item-detail
  = render 'shared/item-detail'
  %p.item-detail__item-description-inner
  = @item.description
  = link_to "商品の編集", edit_item_path(@item), class: "item-detail__buy-button"
  %p or
  = link_to "この商品を削除する", "/items/#{@item.id}", method: :delete, class: "item-detail__buy-button-gray"
#aside.banner-content
  = render 'shared/banner-content'

#footer.footer-content
  = render 'shared/footer'

app/views/users/items.html.haml
.saling-items-info
  .saling-items-info-title
    %h3 出品した商品
  .tabs
    %input#selling_items{type: "radio", name: "items-info-tab-item",checked:"checked"}
    %label.tab_item_3{for: "selling_items"}
      %h3
        出品中
    %input#during_tradings{type: "radio", name: "items-info-tab-item"}
    %label.tab_item_3{for: "during_tradings"}
      %h3
        取引中
    %input#sold_items{type: "radio", name: "items-info-tab-item"}
    %label.tab_item_3{for: "sold_items"}
      %h3
        売却済み
    .tab_content#selling_items_content
      %ul#mypage-tab-selling_items.mypage-item-list.tab-pane
        - @items.each do |item|
          %li
            = link_to "/users/mypage/salingitem/#{item.id}" do
              = image_tag "#{item.item_images[0].image}"
              = item.name
    .tab_content#during_tradings_content
      %ul#mypage-tab-during_tradings.mypage-item-list.tab-pane
        %li.mypage-item-not-found.bold 過去に取引した商品がありません
    .tab_content#sold_items_content
      %ul#mypage-tab-sold_items.mypage-item-list.tab-pane
        %li.mypage-item-not-found.bold 過去に取引した商品がありません

app/views/users/logout.html.haml
.user-logout
  .user-logout-content
    = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn-default btn-red"

app/views/users/profile.html.haml
.profile-content
  %section.profile-content__wrapper
    %h2.profile-content__header プロフィール
    = form_for @user, url: user_registration_path do |f|
      .profile-content__profile-icon-area
        %figure
          =image_tag 'unsetted-user-image.jpg', size: '60x60'
        = f.text_field :nickname, class: "input-default"
      .profile-content__profile-text-area
        = f.text_area :profile, placeholder: "例）こんにちは☆ ご覧いただきありがとうございます！かわいいものやきれいめオフィスカジュアル中心に出品しています。服のサイズは主に9号です。気持ちよくお取引できるよう心がけていますので、商品や発送方法などご質問がありましたらお気軽にどうぞ♪", class: "textarea-default"
        = f.submit "変更する", id: "SaveAccount", class: "btn-default btn-red"

app/views/users/registration.html.haml
.signup-container
  %header.signup-header
    = render '/layouts/accounts/headerLogo'
    %nav.progress-bar.signup-bar
      %ol.clearfix
        %li.active 会員情報
        %li 電話番号認証
        %li 住所入力
        %li 支払い方法
        %li 完了
  %main.signup-main
    %section.l-signup-container
      %h2.l-signup-head 会員情報入力
      %form.l-signup-inner
        .l-signup-content
          .form-group
            %label ニックネーム
            %span.form-require 必須
            %input.input-default{type: "text", placeholder: "例）メルカリ太郎"}
          .form-group
            %label メールアドレス
            %span.form-require 必須
            %input.input-default{type: "email", placeholder: "PC・携帯どちらでも可"}
          .form-group
            %label パスワード
            %span.form-require 必須
            %input.input-default{type: "password", placeholder: "6文字以上"}
          .form-group
            %label パスワード(確認)
            %span.form-require 必須
            %input.input-default{type: "password", placeholder: "6文字以上"}
          .form-group
            .g-recaptcha.signup-recaptcha{data: {sitekey: ""}}
              %div{style:"width: 304px; height: 78px;"}
          %button.btn-default.btn-red{type: "submit"} 次へ進む
  %footer.signup-footer
    = render '/layouts/accounts/footer'

app/views/users/show.html.haml
.user-info.clearfix
  %img.user-background{src:"/images/moyamoya.jpg"}
  .user-image
    %img{src:"/images/unsetted-user-image.jpg"}
    %p
      = @user.nickname
    %p 評価 0 出品数 0
%section.mypage-tab-container-notification-todo.clearfix
  .tabs
    %input#notification{type: "radio", name: "user-info-tab-item",checked:"checked"}
    %label.tab_item_2{for: "notification"}
      %h3
        お知らせ
    %input#todo{type: "radio", name: "user-info-tab-item"}
    %label.tab_item_2{for: "todo"}
      %h3
        やることリスト
    .tab_content#notification_content
      %ul#mypage-tab-notification.mypage-item-list.tab-pane
        %li.mypage-item-not-found.bold 現在、お知らせはありません
    .tab_content#todo_content
      %ul#mypage-tab-todo.mypage-item-list.tab-pane
        %li.mypage-item-not-found.bold 現在、やることリストはありません

.items-info
  .items-info-title
    %h3 購入した商品
  .tabs
    %input#selling_items{type: "radio", name: "items-info-tab-item",checked:"checked"}
    %label.tab_item_2{for: "selling_items"}
      %h3
        取引中
    %input#sold_items{type: "radio", name: "items-info-tab-item"}
    %label.tab_item_2{for: "sold_items"}
      %h3
        過去の取引
    .tab_content#selling_items_content
      %ul#mypage-tab-selling_items.mypage-item-list.tab-pane
        %li.mypage-item-not-found.bold 取引中の商品がありません
    .tab_content#sold_items_content
      %ul#mypage-tab-sold_items.mypage-item-list.tab-pane
        %li.mypage-item-not-found.bold 過去に取引した商品がありません

app/views/users/top.html.haml
.signup-container
  %header.signup-header
    = render '/layouts/accounts/headerLogo'
  %main.signup-main
    %section.l-signup-container
      %h2.l-signup-head 新規会員登録
      .l-signup-inner
        .l-signup-content
          = link_to new_user_registration_path, class: 'btn-default btn-mail' do
            %i.btn-mail.far.fa-envelope
            メールアドレスで登録
          %br/
          = link_to user_facebook_omniauth_authorize_path do
            %btn#facebook-login.btn-default.btn-sns.btn-sns-facebook
              %i.icon-facebook.fab.fa-facebook-f
              Facebookで登録
          %br/
          = link_to user_google_oauth2_omniauth_authorize_path do
            %btn#google-login.btn-default.btn-sns.btn-sns-google
              %i.icon-google-plus.fab.fa-google-plus-g
              Googleで登録
        </button>
  %footer.signup-footer
    = render '/layouts/accounts/footer'