config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords:     'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  root 'items#index'

  resources :items, only: [:show, :index, :new, :create, :edit, :update, :destroy] do
    member do
      get :purchase_top
      post :purchase
    end
    collection do
      get :search
    end
  end

  resources :categories, only: [:show, :index]


  resources :brands, only: [:show, :index]

  get 'users/sign_up_top' => 'users#top'
  get '/users/after_signup' => 'users#after_signup'
  get '/signup/registration' => 'users#registration'
  get '/users/mypage/' => 'users#show'
  get '/users/mypage/identification' => 'users#identification'
  get '/users/mypage/logout' => 'users#logout'
  get '/users/mypage/profile' => 'users#profile'
  get '/users/mypage/card' => 'users#card'
  get '/users/mypage/items' => 'users#items'
  get '/users/mypage/salingitem/:id' => 'users#item'
end

app/views/shared/_banner-content.html.haml
.banner-content__image
  .banner-content__main-box
    %h2 スマホでかんたんフリマアプリ
    %p 今すぐ無料ダウンロード!
    .banner-content__icons-box.clearfix
      .banner-content__mercari-icon
        =image_tag '/images/mercari_icon.png', size: '68x68'
      %ul
        %li
          %a(href='')
            =image_tag '/images/App_icon.png', size: '133x40'
        %li
          %a(href='')
            =image_tag '/images/Google-Play.png', size: '133x40'
  %figure
    =image_tag '/images/banner-phone-image.png', size: '300x260'

app/views/shared/_breadCrumbs.html.haml
.header-breadcrumb
  .header-innner
    - breadcrumb "#{controller.controller_name}_#{controller.action_name}".to_sym
    = breadcrumbs separator: " &rsaquo; "
    

app/views/shared/_footer.html.haml
.footer-content__wrapper
  .footer-content__main
    %ul
      %li.footer-content__main--box
        %h2 メルカリについて
        %ul
          %li
            = link_to "会社概要（運営会社)"
          %li
            = link_to "プライバシーポリシー"
          %li
            = link_to "メルカリ利用規約"
          %li
            = link_to "メルカリ利用規約・有償ポイントに関する特約"
          %li
            = link_to "あんしんスマホサポート制度に関する利用特約"
          %li
            = link_to "コンプライアンスポリシー"
          %li
            = link_to "個人データの安全管理に係る基本方針"
          %li
            = link_to "特定商取引に関する表記"
          %li
            = link_to "資金決済法に基づく表示"
          %li
            = link_to "法令順守と犯罪抑止のために"
          %li
            = link_to "採用情報"
      %li.footer-content__main--box
        %h2 メルカリを見る
        %ul
          %li
            = link_to "カテゴリー一覧"
          %li
            = link_to "ブランド一覧"
          %li
            = link_to "出品地域一覧"
          %li
            = link_to "公式ブログ"
          %li
            = link_to "公式Twitter"
          %li
            = link_to "公式Facebook"
      %li.footer-content__main--box
        %h2 ヘルプ＆ガイド
        %ul
          %li
            = link_to "メルカリガイド"
          %li
            = link_to "メルカリロゴ利用ガイドライン"
          %li
            = link_to "お知らせ"
          %li
            = link_to "らくらくメルカリ便とは"
          %li
            = link_to "ゆうゆうメルカリ便とは"
          %li
            = link_to "大型らくらくメルカリ便とは"
          %li
            = link_to "車体取引ガイド"
          %li
            = link_to "返品・返金ポリシー"
          %li
            = link_to "メルカリあんしん・あんぜん宣言！"
          %li
            = link_to "偽ブランド品撲滅への取り組み"
          %li
            = link_to "メルカリボックス"
      %li.footer-content__main--box
        %h2 国
        %ul
          %li.footer-content__main--box-flag.footer-content__main--box-shadow
            = link_to () do
              =image_tag '/images/flag_us.png', size: '22x22'
              United States
          %li.footer-content__main--box-flag.footer-content__main--box-shadow
            = link_to () do
              =image_tag '/images/flag_uk.png', size: '22x22'
              United Kingdom
          %li.footer-content__main--box-flag
            = link_to () do
              =image_tag '/images/flag_jp.png', size: '22x22'
              日本

= link_to image_tag('/images/mercari_footer.png', size: '160x40'), '',class: 'footer-content__logo'
%p.footer-content__copy-right © 2018 Mercari

app/views/shared/_header.html.haml
.header-innner
  .header-innner__clearfix
    %h1.header-innner__left
      = link_to image_tag('/images/mercari.png'), root_path,class: 'header-innner__link'
    = form_tag(search_items_path, method: :get,class: "header-innner__form") do
      %input(type='search' name='keyword' placeholder='キーワードから探す' class='header-innner__input')
        =fa_icon "search", class: 'header-innner__search-icon'
  .header-innner__clearfix.header-innner__navbox
    %nav.header-innner__left
      %ul.header-innner__nav
        %li.header-innner__nav-category
          %h2
            = link_to "カテゴリーから探す", categories_path, class: 'header-innner__nav-root'
          %ul.header-innner__category-nav
            - cache "index_category_template", expires_in: 20.minutes do
              - Category.roots().each do |parent_category|
                %li.header-innner__category-nav--parent
                  %h3
                    = link_to "#{parent_category.name}", category_path(parent_category),class: "header-innner__category-nav--parent-name"
                  %ul.header-innner__category-nav--child-wrap
                    -parent_category.children.each do |child_category|
                      %li.header-innner__category-nav--child
                        = link_to "#{child_category.name}",category_path(child_category)
                        %ul.header-innner__category-nav--grand-child-wrap
                          -child_category.children.each do |grand_child_category|
                            %li.header-innner__category-nav--grand-child
                              = link_to "#{grand_child_category.name}",category_path(grand_child_category)

        %li.header-innner__nav-bland
          %h2
            = link_to "ブランドから探す", brands_path,class: 'header-innner__nav-root'
          %ul.header-innner__bland-nav
            -Brand.recommend_items_i18n.invert.keys.each do |brand|
              %li.header-innner__bland-nav-list
                %h3
                  = link_to "#{brand}", brand_path(brand, name: brand),class: "header-innner__bland-nav-name"
            %li.header-innner__bland-nav-list
              %h3
                = link_to "ブランド一覧", brands_path,class: "header-innner__bland-nav-name"

    .header-innner__right
      %ul.header-innner__login-nav
        -if user_signed_in?
          %ul.header-innner__login-user
            %li
              =link_to users_mypage_path, class: 'header-innner__mypage'  do
                .header-innner__mypage-link
                  .header-innner__icon-image
                    =image_tag '/images/unsetted-user-image.jpg'
                  .header-innner__mypage-text マイページ
            %li
              =link_to users_mypage_path, class: 'header-innner__notice' do
                %i.far.fa-bell.like-icon.header-innner__icon-bell
                %span お知らせ
            %li
              =link_to users_mypage_path do
                %i.fas.fa-check.header-innner__icon-check
                %span やることリスト
        -else
          %li
            = link_to "ログイン", new_user_session_path,class: 'header-innner__header-btn--login'
          %li.header-innner__signup
            = link_to "新規会員登録", users_sign_up_top_path,class: 'header-innner__header-btn--signup'

app/views/shared/_item-detail.html.haml
%h1.item-detail__title
  =@item.name
%p.item-detail__top-text
  『#{@item.name}』は、
  =link_to @saler.nickname, ""
  さんから出品されました。
  - if @brand.present?
    =link_to "#{@brand.name}(#{@category.name}/#{@parent_category.name})", '#'
    の商品で、#{@item.ships_from_i18n}から#{@item.days_to_ship_i18n}されます。
  - else
    =link_to "#{@category.name}/#{@parent_category.name})", ""
    の商品で、#{@item.ships_from_i18n}から#{@item.days_to_ship_i18n}されます。
.item-detail__main-content.clearfix
  .item-detail__item-photo
    %ul.slider.item-detail__item-photo-main
      -@item_images.each do |item_image|
        %li.slider-list
          =image_tag "#{item_image.image}", size: '300x300'
    %ul.slider-nav.item-detail__item-photo-dots
      -@item_images.each do |item_image|
        %li.item-detail__item-photo-dot
          =image_tag "#{item_image.image}", class: "item-detail__item-photo-bottom", size: '75x75'


  %table.item-detail__item-info
    %tr
      %th 出品者
      %td
        =link_to @saler.nickname, ""
        .item-detail__rating-area
          .item-detail__rating.good
            %i.far.fa-grin
            %span 32
          .item-detail__rating.normal
            %i.far.fa-meh
            %span 22
          .item-detail__rating.bad
            %i.far.fa-frown
            %span 9
    %tr
      %th カテゴリー
      %td
        =link_to do
          =@grandparent_category.name
        =link_to do
          .item-detail__sub-category
            %i.icon-arrow-right
            =@parent_category.name
        =link_to do
          .item-detail__sub-category
            %i.icon-arrow-right
            =@category.name
    %tr
      %th ブランド
      %td
        -if @brand.present?
          =link_to do
            =@brand.name
    %tr
      %th 商品のサイズ
      %td
        =@item.size_i18n
    %tr
      %th 商品の状態
      %td
        =@item.status_i18n
    %tr
      %th 配送料の負担
      %td
        =@item.delivery_fee_method_i18n
    %tr
      %th 配送の方法
      %td
        =@item.delivery_method_i18n
    %tr
      %th 配送元地域
      %td
        =@item.ships_from_i18n
    %tr
      %th 発送日の目安
      %td
        =@item.days_to_ship_i18n

.item-detail__price-box
  %span.item-detail__price-box-price
    = item_price(@item.price)
  %span.item-detail__price-box-tax (税込)
  %span.item-detail__price-box-shipping-fee 送料込み

app/views/shared/_sell-btn.html.haml
= link_to new_item_path, class: 'sell-btn' do
  %p 出品
  =fa_icon 'camera', class: 'sell-btn__icon'