config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    passwords:     'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  root 'items#index'

  resources :items, only: [:show, :index, :new, :create, :edit, :update, :destroy] do
    member do
      get :purchase_top
      post :purchase
    end
    collection do
      get :search
    end
  end

  resources :categories, only: [:show, :index]


  resources :brands, only: [:show, :index]

  get 'users/sign_up_top' => 'users#top'
  get '/users/after_signup' => 'users#after_signup'
  get '/signup/registration' => 'users#registration'
  get '/users/mypage/' => 'users#show'
  get '/users/mypage/identification' => 'users#identification'
  get '/users/mypage/logout' => 'users#logout'
  get '/users/mypage/profile' => 'users#profile'
  get '/users/mypage/card' => 'users#card'
  get '/users/mypage/items' => 'users#items'
  get '/users/mypage/salingitem/:id' => 'users#item'
end

app/models/item.rb
class Item < ApplicationRecord

  validates :name, presence: true
  validates :price, presence: true
  belongs_to :buyer, class_name: "User", optional: true
  belongs_to :saler, class_name: "User"
  validates :saler_id, presence: true

  has_many :item_images, dependent: :destroy, inverse_of: :item
  accepts_nested_attributes_for :item_images, allow_destroy: true, reject_if: proc { |attributes| attributes['image'].blank? && attributes['image_cache'].blank?}
  validates :item_images, length: { minimum: 1 }

  belongs_to :category

  belongs_to :brand, optional: true

  enum status: { unused: 1,  close_to_unused: 2,  no_noticeable_scratch_or_dirt: 3,  slightly_scratch_or_dirt: 4,  scratch_or_dirt: 5,  bad_condition: 6}

  enum delivery_fee_method: { shipping_included: 1, cash_on_delivery: 2  }

  enum days_to_ship:{
    shipped_within_1_to_2_days: 1,
    shipped_within_2_to_3_days: 2,
    shipped_within_4_to_7_days: 3
  }


  enum size: {
    XXS_or_less: 1,
    XXS_or_SS: 2,
    S: 3,
    M: 4,
    L: 5,
    XL_or_LL: 6,
    two_XL_or_three_L: 7,
    three_XL_or_four_L: 8,
    four_XL_or_five_L_or_more: 9,
    free: 10
  }


  enum ships_from:{
    hokkaido: 1, aomori: 2, iwate: 3, miyagi: 4, akita: 5, yamagata: 6, fukushima: 7, ibaraki: 8,
    tochigi: 9, gunnma: 10, saitama: 11, chiba: 12, tokyo: 13, kanagawa: 14, nigata: 15, toyama: 16,
    ishikawa: 17, fukui: 18, yamanashi: 19, nagano: 20, gifu: 21, sizuoka: 22, aichi: 23 ,mie: 24,
    shiga: 25, kyoto: 26 ,osaka: 27 , hyogo: 28 ,nara: 29 ,wakayama: 30 ,tottori: 31,shimane: 32,
    okayama: 33, hiroshima: 34, yamaguchi: 35 , tokushima: 36, kagawa: 37 ,ehime: 38 ,kochi: 39, fukuoka: 40,
    saga: 41,nagasaki: 42, kumamoto: 43, oita: 44, miyazaki: 45, kagoshima: 46, okinawa: 47
  }


  enum delivery_method:{
    pending: 1,
    kuronekoyamato: 2,
    yu_pack: 3,
    yu_mail: 4
  }

  def self.items_search_by_brand(brands)
    brands.map {|brand| brand.items}
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :authenticate_user!, only: [:purchase_top,:purchase]

  before_action :require_login, only: [:new, :create]
  before_action :set_item, only: [:show, :edit, :destroy]
  before_action :check_user_id, only: [:edit, :destroy]

  before_action :find_item, only: [:purchase_top, :purchase, :update]

  def index
    @items = Item.includes(:item_images).all
    @parent_categories = Category.roots()
    @brand_items = @items.where.not(brand_id: nil)
  end

  def show
    set_category
    @saler = @item.saler
    @brand = @item.brand
  end

  def purchase_top
    @item_image = @item.item_images.first
  end

  def purchase
    @token = params['payjpToken']

    if current_user.purchase(@item,@token)
      redirect_to root_path
    else
      redirect_to new_user_session_path
    end
  end

  def update
    if @item.update(item_params)
      redirect_to action: :show
    else
      @item_image_new = ItemImage.new(item_id: @item.id)
      set_category
      @item_image_length = "have-item#{@item.item_images.length}"
      render :edit
    end
  end

  def new
    @item = Item.new
    @item_image_new = ItemImage.new(item_id: @item.id)
    @item_image_length = "have-item0"
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      @item_image_new = ItemImage.new(item_id: @item.id)
      @item_image_length = "have-item0"
      render action: :new
    end
  end

  def edit
    @item_images.each do |item_image|
      item_image.image.cache!
    end
    @item_image_new = ItemImage.new(item_id: @item.id) 
    set_category
    @item_image_length = "have-item#{@item.item_images.length}"
  end

  def destroy
    if @item.destroy
      redirect_to root_path
    end
  end

  def search
    @keyword = params[:keyword]
    # 検索値をアイテム名に含むitem
    items_search_by_item_name = Item.where('name LIKE(?)', "%#{@keyword}%").limit(20)

    @brands = Brand.where('name LIKE(?)', "%#{params[:keyword]}%")

    if @brands.present?
      # 検索値をブランド名に含むitem
      items_search_by_brand = Item.items_search_by_brand(@brands)
      # 最終的に表示するitem
      @items = items_search_by_item_name | items_search_by_brand[0] 
    else
      @items = items_search_by_item_name
    end  
  end

  private
  def require_login
    redirect_to new_user_session_url unless user_signed_in?
  end

  def item_params
    item_params = params.require(:item).permit(:name,:description,:category_id,:size,:status,:delivery_fee_method,:delivery_method,:ships_from,:days_to_ship,:price, item_images_attributes:[:id,:image,:image_cache, :_destroy]
      ).merge(saler_id: current_user.id).merge(brand_id: set_brand_id)
  end

  def set_item_images(item)
    images = params[:item][:item_images_attributes]["0"]
    item_images = []
    images.each do |image|
      item_images << item.item_images.build(image: image)
    end
    return item_images
  end

  def set_brand_id
    Brand.where('name = ?', params[:brand_name])
  end

  def set_item
    @item = Item.includes(:item_images).find(params[:id])
    @item_images = @item.item_images
  end

  def set_category
    @root_categories = Category.roots
    @category = @item.category
    @parent_category = @category.parent
    @grandparent_category = @category.root
  end

  def find_item
    @item = Item.find(params[:id])
  end

  def check_user_id
     redirect_to  new_user_session_url unless @item.saler_id == current_user.id
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_alert-for-sale.html.haml
%p
  = link_to '禁止されている出品', "/jp/help_center/getting_started/prohibited_items/", target: "_blank"
  、
  = link_to '行為', '/jp/help_center/getting_started/prohibited_conduct/', target: '_blank'
  を必ずご確認ください。
%p
  またブランド品でシリアルナンバー等がある場合はご記載ください。
  = link_to '偽ブランドの販売', '/jp/help_center/getting_started/counterfeit_goods/', target: '_blank'
  は犯罪であり処罰される可能性があります。
%p
  また、出品をもちまして
  = link_to '加盟店規約', '/jp/seller_terms/'
  に同意したことになります。

app/views/items/_category-template.html.haml
- Category.roots().each do |root_category|
  %template{id: "child0fCategory#{root_category.id}"}
    = select_tag '' , options_from_collection_for_select(Category.children_of(root_category), :id, :name), name: "parent_category", class: 'select-default select-category'
- Category.roots().each do |root_category|
  - root_category.children().each do |parent_category|
    %template{id: "child0fCategory#{parent_category.id}"}
      = select_tag '', options_from_collection_for_select(Category.children_of(parent_category), :id, :name), name: "item[category_id]", class: 'select-default'

app/views/items/_items.html.haml
%section.items
  %h2.items__head ピックアップカテゴリー
  %section.items__box.clearfix
    %h3.items__title-text
      = link_to '新着アイテム', categories_path
    .items__box-contents.clearfix
      -@items.each do |item|
        = render '/items/form/item-box', item: item
    .items__view-all
      = link_to "すべての商品を見る", categories_path

%section.items
  %h2.items__head ピックアップブランド
  %section.items__box.clearfix
    %h3.items__title-text
      = link_to '新着アイテム'
    .items__box-contents.clearfix
      -@brand_items.each do |brand_item|
        = render '/items/form/item-box', item: brand_item
    .items__view-all
      = link_to "すべての商品を見る"

app/views/items/_top-images.html.haml
%section.top-images
  .top-images__outer
    %div(class='top-images__area')
      .top-images__item
        .top-images__main-image
          .top-images__main-image-wrapper
            .top-images__text-content
              %h2
                スマホでかんたん
                %br>/
                フリマアプリ
              %p
                メルカリはスマホカメラからすぐに出品できる
                %br>/
                購入時も安心な独自システムのアプリです
              .top-images__download-btn.clearfix
                = link_to image_tag('/images/App_icon_top.png'),'',class: 'btn-left'
                = link_to image_tag('/images/Google-Play.png'),'',class: 'btn-right'
            =image_tag '/images/phone_image_top.png', class: 'top-images__phone-image'
      .top-images__item.banner-kusanagi
        = link_to image_tag('/images/kusanagi.jpg'),'',class: 'top-banner banner-kusanagi'
      .top-images__item
        = link_to image_tag('/images/bokurano-heisei.jpg'),'',class: 'top-banner banner-bokurano-heisei'
      .top-images__item
        = link_to '','',class: 'top-banner banner-welcome'

app/views/items/edit.html.haml
= render '/items/form/itemFormsContainer', {item: @item}

app/views/items/index.html.haml
%header.header-content
  = render 'shared/header'

#main.main-content
  = render 'top-images'

#aside.items-content
  = render 'items'

#aside.banner-content
  = render 'shared/banner-content'

#footer.footer-content
  = render 'shared/footer'

= render 'shared/sell-btn'

app/views/items/new.html.haml
.item-new-container
  %header.item-new-header
    = render '/layouts/accounts/headerLogo'
  %main.item-new-main
    = form_for(@item, url: items_path, method: :post, html:{class: 'sell-form'}) do |f|
      %section.l-item-new-container.buy-item-container
        #sell-container
          %div
            .sell-container-inner
              %h2.l-item-new-head 商品の情報を入力
              %form.sell-form
                = render '/items/form/item-images', {f: f}
                = render '/items/form/item-overview', {f: f}
                = render '/items/form/item-details', {f: f}
                = render '/items/form/item-delivery', {f: f}
                = render '/items/form/item-price', {f: f}
                .modal{:role => "dialog", :tabindex => "-1"}
                  .modal-inner
                .sell-content.sell-btn-box
                  %div
                  = render partial: '/items/alert-for-sale'
                  = f.submit '出品する', class: 'btn-default btn-red'
                  %a.btn-default.btn-gray もどる
  %footer.item-new-footer
    = render '/layouts/accounts/footer'
  %template#image-list-item
    %li.sell-upload-item
      %figure.sell-upload-figure.landscape
        .img{class: '', html:{ src:'', alt:''}}
        .sell-upload-button
          %a.sell-upload-edit 編集
          %a.sell-upload-edit 削除
  = render partial: '/items/category-template'

app/views/items/purchase_top.html.haml
.purchase_top
  %header.purchase_top__header
    %h1
      = link_to image_tag('/images/mercari_gray.png'),root_path
  %main.purchase_top__main
    %section.purchase_top__main-container
      %h2.purchase_top__main-header 購入を確定しますか？
      %section.purchase_top__main-item
        .purchase_top__main-item-inner
          %h3.purchase_top__main-item-image
            = image_tag "#{@item_image.image}"
          %p.purchase_top__main-item-name
            = @item.name
          .purchase_top__main-item-buy
            %p.purchase_top__main-item-price
              = item_price(@item.price)
              %span.purchase_top__main-item-shipping-fee 送料込み
            %ul.purchase_top__main-item-table
              %li
                .purchase_top__main-item-pay-text 支払い金額
                .purchase_top__main-item-pay-price
                  %span 
                    = item_price(@item.price)
            = form_tag(purchase_item_path, method: :post, id: "charge-form") do
              %script{src: "https://js.pay.jp/", type: "text/javascript"}
              %span.charge-errors
              %h4  
              %input.number{ value: "#{current_user.credit_card_num}", name: "number", type: "text", id: "num",type: "hidden"}/
              %input.cvc{ maxlength: "3", name: "cvc", value: "#{current_user.credit_card_security_num}", type: "text", id: "cvc",type: "hidden"}/
              %input.exp_month{ maxlength: "2", name: "exp_month", value: "#{current_user.credit_card_expiration_month}", type: "text", id: "exp_month",type: "hidden"}/
              %input.exp_year{ maxlength:"4", name: "exp_year", value: "20#{current_user.credit_card_expiration_year}", type: "text", id: "exp_year",type: "hidden"}/
              %input.token{type: "hidden", name: "payjpToken", id: "token",type: "hidden"}/
              %input{type: "submit", class: "submit_button btn-red", value: "購入する"} 
    
      %section.purchase_top__user-info
        .purchase_top__user-info-inner
          %h3 配送先
          .purchase_top__user-address
            .purchase_top__user-address--postal_code
              = current_user.postal_code
            %p.purchase_top__user-address--city
              = current_user.city
            %p.purchase_top__user-address--address
              = current_user.address
            %p.purchase_top__user-address--building-name
              = current_user.building_name
          .purchase_top__user-name
            %p.purchase_top__user-name--first
              = current_user.first_name
            %p.purchase_top__user-name--last
              = current_user.last_name
          = link_to "" do
            変更する
            %i.icon-arrow-right
      %section.purchase_top__method
        .purchase_top__method-inner
          %h3 支払い方法
          %p.purchase_top__method-card-num
            = current_user.credit_card_num
          %p.purchase_top__method-card-month
            = current_user.credit_card_expiration_month
          %p.purchase_top__method-card-bar /
          %p.purchase_top__method-card-year
            = current_user.credit_card_expiration_year
          %figure
            = image_tag '/images/visa.png'
          = link_to "" do
            変更する
            %i.icon-arrow-right  

  %footer.purchase_top__footer
    %nav
      %ul.clearfix
        %li
          = link_to "プライバシーポリシー",""
        %li.footer-list
          = link_to "メルカリ利用規約",""
        %li.footer-list
          = link_to "特定商取引に関する表記",""
    = link_to image_tag('/images/mercari_footer_gray.png'), root_path, class: "footer-image"
    %p © 2019 Mercari

app/views/items/search.html.haml
%header.header-content
  = render 'shared/header'
  .header-breadcrumb
    .header-innner
      - breadcrumb :items_search, @keyword
      = breadcrumbs separator: " &rsaquo; "

#main.search-container.clearfix
  .search-container__item-content.clearfix
    %h2.search-container__header 検索結果#{@items.length}件
    .search-container__items.clearfix
      -@items.each do |item|
        = render 'items/form/item-box', item: item

  .search-container__side-content


#aside.banner-content
  = render 'shared/banner-content'

#footer.footer-content
  = render 'shared/footer'

=link_to new_item_path, class: 'sell-btn' do
  = render 'shared/sell-btn'

app/views/items/show.html.haml
%header.header-content
  = render 'shared/header'
  .header-breadcrumb
    .header-innner
      - breadcrumb "#{controller.controller_name}_#{controller.action_name}".to_sym,
        @item
      = breadcrumbs separator: " &rsaquo; "
%section.item-detail
  = render 'shared/item-detail'
  - if @item.buyer_id 
    =link_to "売り切れました", "", class: "item-detail__buy-button-gray"
  - else
    =link_to "購入画面に進む", purchase_top_item_path, class: "item-detail__buy-button"
  .item-detail__item-description
    %p.item-detail__item-description-inner
    =@item.description
  .item-detail__item-button.clearfix
    .item-detail__item-button-left
      =link_to "", class: "item-detail__like-button" do
        %i.far.fa-heart.like-icon
        %span いいね！
        %span 14
      =link_to "", class: "item-detail__flag-button" do
        %i.far.fa-flag.flag-icon
        %span 不適切な商品の報告
    .item-detail__item-button-right
      =link_to do
        %i.fas.fa-lock.lock-icon
        %span あんしん・あんぜんへの取り組み

#aside.banner-content
  = render 'shared/banner-content'

#footer.footer-content
  = render 'shared/footer'